/// <reference types="cypress" />
beforeEach(() => {
  cy.visit('https://tgpaymentuat.2c2p.com/TestSimulator/')
})
describe('ThaiAirways.Kbank', () => {
  it('Kbank1A.Approve', () => {
    cy.contains('AMADEUS Redirect Payment').click()
    cy.get('#EXTERNAL_ID2').type("2C2PYOK")
    cy.get('#btnSubmit').click()
    cy.get('#credit_card_number').type(Cypress.env('card1'))
    cy.get('#credit_card_holder_name').click().type(Cypress.env('name'))
    cy.get('#credit_card_expiry').type('1223')
    cy.get('#credit_card_cvv').type('123')
    cy.get('#credit_card_issuing_bank_country').select('THAILAND')
    cy.get('#credit_card_issuing_bank_name').type('SCB')
    cy.contains('Confirm Payment').click()
    cy.get('#btnHideModal').click()
    cy.get('Ul').contains('Approved').should('be.visible')
  })
  it('Kbank1A.Reject', () => {
    cy.contains('AMADEUS Redirect Payment').click()
    cy.get('#EXTERNAL_ID2').type("2C2PYOK")
    cy.get('#btnSubmit').click()
    cy.get('#credit_card_number').type(Cypress.env('card1'))
    cy.get('#credit_card_holder_name').click().type(Cypress.env('name'))
    cy.get('#credit_card_expiry').type('1223')
    cy.get('#credit_card_cvv').type('123')
    cy.get('#credit_card_issuing_bank_country').select('THAILAND')
    cy.get('#credit_card_issuing_bank_name').type('SCB')
    cy.contains('Confirm Payment').click()
    //cy.get('#btnHideModal').click()
    //cy.get('Ul').contains('Rejected').should('be.visible')
  })
})
describe('Ins.2C2P', () => {
  it('Ins.1A', () => {
    cy.contains('AMADEUS Redirect Payment').click()
    cy.get('#EXTERNAL_ID2').type("BKKH2TG")
    cy.get('#AMOUNT_AIR').clear().type('5000')
    cy.get('#LIST_INSURANCE_AMOUNT_1').clear().type('1000')
    cy.get('#btnSubmit').click()
    cy.get('#credit_card_number').type(Cypress.env('card1'))
    cy.get('#credit_card_holder_name').click().type(Cypress.env('name'))
    cy.get('#credit_card_expiry').type('1223')
    cy.get('#credit_card_cvv').type('123')
    cy.get('#credit_card_issuing_bank_country').select('THAILAND')
    cy.get('#credit_card_issuing_bank_name').type('SCB')
    cy.contains('Confirm Payment').click()
    cy.get('#otp').type('123456')
    cy.get('#continue').click()
    cy.get('#btnHideModal').click()
    cy.get('Ul').contains('Approved').should('be.visible')
  })
})
describe('ThaiAirways.UnionPay', () => {
  it('UPI.Approved', () => {
    cy.contains('AMADEUS Redirect Payment').click()
    cy.get('#EXTERNAL_ID2').type("2C2PYOK")
    cy.get('#btnSubmit').click()
    cy.scrollTo(0, 1500)
    cy.wait(500)
    cy.contains('E-WALLET').click()
    //SHOULDBE UPI
    cy.contains('CONTINUE').click()
    cy.get('#cardNumber').type(Cypress.env('card3')).should('have.value', Cypress.env('card3'))
    cy.get('#btnNext').click()
    cy.get('#expireMonth').type('12')
    cy.get('#expireYear').type('33')
    cy.get('#expireYear').type('33')
    cy.get('#cvn2').type('123')
    cy.get('#btnGetCode').click()
    cy.wait(500)
    cy.get('#smsCode').type('111111')
    cy.get('[type="checkbox"]').check()
  })
})